// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID        pgtype.UUID
	FolderID  pgtype.UUID
	Title     string
	Body      string
	OwnerSub  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Folder struct {
	ID        pgtype.UUID
	ParentID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
