// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	DeleteDocument(ctx context.Context, id pgtype.UUID) (int64, error)
	GetDocument(ctx context.Context, id pgtype.UUID) (Document, error)
	GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error)
	ListDocuments(ctx context.Context) ([]Document, error)
	ListDocumentsInFolder(ctx context.Context, folderID pgtype.UUID) ([]Document, error)
	ListFolders(ctx context.Context) ([]Folder, error)
	// COALESCE+NULLIF lets the caller pass '' to mean "leave field unchanged".
	// Matches the previous in-memory Store's "empty = no change" semantics.
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
}

var _ Querier = (*Queries)(nil)
