// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (folder_id, title, body, owner_sub)
VALUES ($1, $2, $3, $4)
RETURNING id, folder_id, title, body, owner_sub, created_at, updated_at
`

type CreateDocumentParams struct {
	FolderID pgtype.UUID
	Title    string
	Body     string
	OwnerSub string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.FolderID,
		arg.Title,
		arg.Body,
		arg.OwnerSub,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Title,
		&i.Body,
		&i.OwnerSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, folder_id, title, body, owner_sub, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Title,
		&i.Body,
		&i.OwnerSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolder = `-- name: GetFolder :one
SELECT id, parent_id, name, created_at, updated_at
FROM folders
WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, folder_id, title, body, owner_sub, created_at, updated_at
FROM documents
ORDER BY created_at
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Body,
			&i.OwnerSub,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsInFolder = `-- name: ListDocumentsInFolder :many
SELECT id, folder_id, title, body, owner_sub, created_at, updated_at
FROM documents
WHERE folder_id = $1
ORDER BY created_at
`

func (q *Queries) ListDocumentsInFolder(ctx context.Context, folderID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Body,
			&i.OwnerSub,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, parent_id, name, created_at, updated_at
FROM folders
ORDER BY created_at
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title      = COALESCE(NULLIF($1::text, ''), title),
    body       = COALESCE(NULLIF($2::text, ''), body),
    updated_at = now()
WHERE id = $3
RETURNING id, folder_id, title, body, owner_sub, created_at, updated_at
`

type UpdateDocumentParams struct {
	Title string
	Body  string
	ID    pgtype.UUID
}

// COALESCE+NULLIF lets the caller pass ” to mean "leave field unchanged".
// Matches the previous in-memory Store's "empty = no change" semantics.
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument, arg.Title, arg.Body, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Title,
		&i.Body,
		&i.OwnerSub,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
